### ISSUE TITLE
rest api documentation

### ISSUE THREAD

**Issue by modernecotech** [SamStudio8/ocarina#3]
Hi

I'm trying to upload the sample metadata/library metadata and sequencing metadata to the climb server with a rest api. I saw the ocarina API, but it seems to be mostly for CLI based uploads of individual records. 

Could you clarify where I can find the production endpoint and api to correctly upload the sample, library & sequencing metadata.

**Comment by SamStudio8** [comment]
Hi @modernecotech, the API documentation is here: https://docs.covid19.climb.ac.uk/majora-api
